# Use the NVIDIA Triton Inference Server base image
FROM nvcr.io/nvidia/tritonserver:23.08-py3


RUN python3 -m pip install --upgrade pip
RUN pip3 install --upgrade pip

# Install required Python libraries
RUN pip3 install gensim==4.3.3

# Additional libraries for compatibility
RUN pip3 install typing-extensions


