services:
  triton:
    image: jp4f-triton-api
    volumes:
      - /Users/viet-quanggg/Downloads/w2c_module/triton_folder_w2v:/models
    ports:
      - "1234:8000"
      - "1235:8001"
      - "1236:8002"
    command: tritonserver --model-repository=/models --http-port 8000 --grpc-port 8001 --metrics-port 8002
