name: "doc2vec"
max_batch_size: 0
backend: "python"

input [
{
    name: "TEXT"
    data_type: TYPE_STRING
    dims: [-1]
}
]

output [
{
    name: "VECTORIZE"
    data_type: TYPE_INT32
    dims: [-1]
}
]

instance_group [
    {
      kind: KIND_CPU
    }
]